server:
  port: 8082
---

spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: 'Welcome to Spring Boot Full Tutorial'

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: 'beans,env'

---

  spring:
    profiles: qa
    datasource:
      username: root
      url: jdbc:mysql://localhost:3306/dcbapp-qa
      driverClassName: com.mysql.cj.jdbc.Driver
      password: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: 'true'
  welcome:
    message: 'Welcome to Spring Boot Full Tutorial'

---

  spring:
    profiles: prod
    datasource:
      username: root
      url: jdbc:mysql://localhost:3306/dcbapp-prod
      driverClassName: com.mysql.cj.jdbc.Driver
      password: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: 'true'
  welcome:
    message: 'Welcome to Spring Boot Full Tutorial'


