spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: '"Welcome to Spring Boot Full Tutorial"'
